### ISSUE TITLE
File is loaded in another buffer

### ISSUE THREAD

**Issue by sebastianbeyer** [chrisbra/CheckAttach#20] opened 2018-06-04 08:10 UTC
```
Error detected while processing function <SNR>56_CheckAttach[74]..<SNR>56_WriteBuf:
line    2:
E139: File is loaded in another buffer
```
This happens if I have one of the keywords in the mail and then enter <Space> to open the filebrowser (ranger). But I can just ignore it and ranger opens. When I select the file in ranger then the process terminates with nonzero exit status, but the file is attached.
If I use `:AttachFile` everything works as expected.
This happens in neovim.

**Comment by chrisbra** [comment] 2018-06-07 21:27
I cannot reproduce this in Vim. Can you please check, whether this happens in Vim?

**Comment by chrisbra** [comment] 2018-06-20 19:02
closing as unreproducible

**Closed by chrisbra** 2018-06-20 19:02 UTC
